# Path settings
data_path: "./resume_model/datasets/UpdatedResumeDataSet.csv"
model_path: "./resume_model/trained_models/model.pkl"
vectorizer_path: "./resume_model/trained_models/vectorizer.pkl"

# Model settings
model_type: "LogisticRegression"
tfidf_max_features: 3000

# Logging settings
logging_level: "INFO"

# Training settings
train_test_split_ratio: 0.8
random_seed: 42
